### ISSUE TITLE
Error on providing Microsoft Graph oData metadata url

### ISSUE THREAD

**Issue by niyati-shah-95** [elasticio/odata2openapi#18]
Hi, I have tried using the microsoft graph metadata url - https://graph.microsoft.com/v1.0/$metadata
I have written my script in js as follows:
```
const { odata2openapi } = require('odata2openapi');

odata2openapi('https://graph.microsoft.com/v1.0/$metadata')
  .then(swagger => console.log(JSON.stringify(swagger, null, 2)))
  .catch(error => console.error(error))
```

**I get the following error on the console:**

```
TypeError: Cannot read property 'find' of undefined
    at C:\Users\kh2339\node_modules\odata2openapi\dist\convert.js:396:54
    at Array.forEach (<anonymous>)
    at addContainmentPathsRecursive (C:\Users\kh2339\node_modules\odata2openapi\dist\convert.js:392:164)
    at C:\Users\kh2339\node_modules\odata2openapi\dist\convert.js:569:13
    at Array.forEach (<anonymous>)
    at pathsRecursive (C:\Users\kh2339\node_modules\odata2openapi\dist\convert.js:527:16)
    at Object.convert [as default] (C:\Users\kh2339\node_modules\odata2openapi\dist\convert.js:882:17)
    at C:\Users\kh2339\node_modules\odata2openapi\dist\index.js:17:120
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by dzardoya** [comment]
Hi niyati,

I have the same issue, I also tried changing to https://graph.microsoft.com/beta/$metadata but obtained the same error... have you manage to solve that?

Regards
